spring:
  application:
    name: ticketing_system_db

  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_system_db
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  # 🟢 Moved under 'spring:'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.hypercell.event_ticketing_platform

# 🟢 Moved to root level
file:
  upload-dir: uploads